import type { Grade, Stream, SubjectId } from './types'
import BOOKS from './ncert.json'

export interface NcertChapter {
  ch: number
  title: string
  pages: number
  sizeMb: number
  /** Direct link to the PDF on ncert.nic.in. */
  href: string
}

export interface NcertBook {
  /** NCERT's own book code, e.g. `keph1` — also the accordion key. */
  code: string
  grade: Grade
  subject: SubjectId
  stream: Stream
  /** "Part I", "Hornbill" — empty when the subject has a single book. */
  label: string
  chapters: NcertChapter[]
  fullBookHref?: string
}

/**
 * Chapterwise index of the NCERT Class 11 and 12 books.
 *
 * Generated by `scripts/build-ncert.py`, which probes every chapter URL on
 * ncert.nic.in and reads each title out of the PDF itself — so the list tracks
 * the current rationalised syllabus instead of a remembered table of contents.
 * Nothing is copied here; these are links to NCERT's own files.
 */
export const NCERT_BOOKS: NcertBook[] = (BOOKS as RawBook[]).map((b) => ({
  code: b.code,
  grade: b.grade as Grade,
  subject: b.subject as SubjectId,
  stream: b.stream as Stream,
  label: b.label,
  fullBookHref: `https://ncert.nic.in/textbook.php?${b.code}=0-${b.chapters.length}`,
  chapters: b.chapters.map((c) => ({
    ch: c.ch,
    title: c.title,
    pages: c.pages,
    sizeMb: c.sizeMb,
    href: `https://ncert.nic.in/textbook/pdf/${b.code}${String(c.ch).padStart(2, '0')}.pdf`,
  })),
}))

interface RawBook {
  code: string
  grade: number
  subject: string
  stream: string
  label: string
  chapters: { ch: number; title: string; pages: number; sizeMb: number }[]
}

export const NCERT_CHAPTER_COUNT = NCERT_BOOKS.reduce((n, b) => n + b.chapters.length, 0)

/** Books for one class, optionally narrowed to a stream. */
export function booksFor(grade: Grade, stream?: Stream): NcertBook[] {
  return NCERT_BOOKS.filter(
    (b) => b.grade === grade && (!stream || b.stream === stream || b.stream === 'common'),
  )
}
